services:
  mysql:
    image: mysql:8.0
    container_name: travel-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: travel_db
      MYSQL_USER: travel_user
      MYSQL_PASSWORD: travel1234
    volumes:
      - ./init:/docker-entrypoint-initdb.d   # init.sql 연결
      - mysql-data:/var/lib/mysql            # 데이터 영속화

volumes:
  mysql-data:
